### ISSUE TITLE
AttributeError (Var error with '.split')

### ISSUE THREAD

**Issue by Keiishu** [bierdok/gnotify#1]
Installed it from github with pip3.

The script just won't start, showing the following error : 
```Traceback (most recent call last):
  File "/home/pi/.local/bin/gnotify", line 11, in <module>
    load_entry_point('gnotify==0.1.0', 'console_scripts', 'gnotify')()
  File "/home/pi/.local/lib/python3.7/site-packages/gnotify/gnotify.py", line 20, in main
    ips = os.getenv("GNOTIFY_IPS").split(',')
AttributeError: 'NoneType' object has no attribute 'split'
```

Apparently, it's caused by trying to split a null string. And in fact, the environment variables the script is trying to read are null, like `GNOTIFY_LANG` or `GNOTIFY_IPS`.

Running on a RPi 3B+ r1.2 with Raspbian Buster
Python 3.7.3 / pip 18.1

EDIT : Works with exporting manually the env variables. For exemple : 
`export GNOTIFY_LANG="fr-FR"`
`export GNOTIFY_IPS="192.168.1.4"`

**Comment by bierdok** [comment]
Hello @Keiishu ,
This issue has been fixed. #b46eb6c5028caba29df8e3605509a3666b93bd08
