### ISSUE TITLE
dependences needed in docker? 

### ISSUE THREAD

**Issue by DAVIZINH0** [bierdok/gnotify#2]
hello
this is ver y usefull for me a Works perfect in a raspberry.
but o try to run it in a docker container (domoticz) and not run. Maybe gnotify need any aditional librarys to run?

when i launch the comand no thing happends :-( not error but not sound

thanks

**Comment by bierdok** [comment]
Hello @DAVIZINH0 ,
This issue has been fixed: https://github.com/bierdok/gnotify/commit/b46eb6c5028caba29df8e3605509a3666b93bd08
